spring:
  application:
    name: FullName
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer_test_db
    username: postgres
    password: postgres525
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  port: 8080

lombok:
  accessors:
    chain: true
